# coding: utf-8

"""
    Swagger bookstore

    This is a sample server bookstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.7
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.book_api import BookApi


class TestBookApi(unittest.TestCase):
    """BookApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BookApi()

    def tearDown(self) -> None:
        pass

    def test_addbook(self) -> None:
        """Test case for addbook

        Add a new book to the store
        """
        pass

    def test_deletebook(self) -> None:
        """Test case for deletebook

        Deletes a book
        """
        pass

    def test_findbooks_by_status(self) -> None:
        """Test case for findbooks_by_status

        Finds books by status
        """
        pass

    def test_findbooks_by_tags(self) -> None:
        """Test case for findbooks_by_tags

        Finds books by tags
        """
        pass

    def test_getbook_by_id(self) -> None:
        """Test case for getbook_by_id

        Find book by ID
        """
        pass

    def test_updatebook(self) -> None:
        """Test case for updatebook

        Update an existing book
        """
        pass

    def test_updatebook_with_form(self) -> None:
        """Test case for updatebook_with_form

        Updates a book in the store with form data
        """
        pass


if __name__ == '__main__':
    unittest.main()
