# coding: utf-8

# flake8: noqa
"""
    Swagger bookstore

    This is a sample server bookstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.7
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model packag
#
#
#
#from order import Order
#from tag import Tag
#from user import User
from openapi_client.models.api_response import ApiResponse
